name: chat-analytics
channels:
  - conda-forge
dependencies:
  - boto3
  - flask-restx
  - flask=2.1.2
  - flask_cors
  - gevent
  - gunicorn
  - isort
  - pip
  - pytest
  - python=3.10
  - requests
  - openai
  - werkzeug=2.1.2
  - tiktoken
  - pip:
      - celery
      - config-probe
      - pytest-cov
      - tox-conda
      - redis
      - git+https://github.com/korbit-ai/python-config-probe.git
